// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_v1_live_index from "./routes/api/v1/live/index.ts";
import * as $index from "./routes/index.tsx";
import * as $LogoWidget from "./islands/LogoWidget.tsx";
import * as $Main from "./islands/Main.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/v1/live/index.ts": $api_v1_live_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/LogoWidget.tsx": $LogoWidget,
    "./islands/Main.tsx": $Main,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
